<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>

<!DOCTYPE html>
<html>
<head>
</head>
<body ng-app="myApp">
	<div class="wrapper">

		<div class="container">
			<div class="page-header">
				<h2>About Us</h2>
			</div>


			<div class="row">
				<div class="well">
					<h3
						style="color: maroon; font-family: fantasy; font-style: 
						oblique; margin-top: -10px; margin-bottom: -10px">
						<i class="fa fa-comments fa-2x"></i> Our Story
					</h3>
					<hr>
					<div align="justify">
						<p>
							&nbsp; <i class="fa fa-check-circle" aria-hidden="true"></i>
							Website - equityjudge.com is a product, brought out by Qualde
							Digital Services Private Limited. This platform is aimed at
							serving the general investing community who are not expert in
							taking decision with regard to equity investing. Recognising the
							futility and inadequacy of cacophony generated by business news
							channels, print media and various stock market participants, we
							decided to work in the direction of automating the investment
							decision making. The Effort can be described as "EQUITY
							INVESTMENT MADE EASY" in nut shell .The investor can arrive at
							investment decision by using this platform which will be well
							informed , sound and even better than the expert advice. The
							suggestions made on the platform are devoid of emotions,
							sentiments and any element of vested interest.
						</p>

						<p>
							&nbsp; <i class="fa fa-check-circle" aria-hidden="true"></i> We
							believe this platform will fill the vital gap in the available
							options to the investors. It operates purely on in-house
							developed computer algorithms. These are predictive algorithms
							developed on pattern recognition techniques. The efficacy of the
							algorithms has been found to be correct in the range of 80-100%.
						</p>
					</div>
					<hr>
					<div align="justify">
						<p
							style="color: green; font-family: sans-serif; font-size: medium;">
							<i class="fa fa-users" aria-hidden="true"></i> But we had a dream
						</p>
						<p>
							&nbsp; <i class="fa fa-hand-o-right" aria-hidden="true"></i>
							After long time of research and dedication by expertise of the
							stock market , we came to final conclusion to develop an
							application which gives you a lot .Our expert team gathered
							requirement from the various source like stock expertise ,
							investors , checking previous records of the stock-Market etc.
							And decided to develop an application which provides algorithmic
							suggestion based on the stock value. Finally we reached a
							stage wherein the team of developers(coders) realized the dream of expert team. 
						</p>
					</div>
					<hr>
					<div align="justify">
						<p
							style="color: green; font-family: sans-serif; font-size: medium;">
							<i class="fa fa-road" aria-hidden="true"></i> And we believe we
							are on the right track.
						</p>

						<p>
							&nbsp;<i class="fa fa-hand-o-right" aria-hidden="true"></i></i>
							Today's we are in the position to examine the stock market
							behavior and provides algorithmic prediction that gives the
							satisfactory result . Our expert team and third Party expert team
							tested every aspect of our application.
						</p>
					</div>
					<hr>
					<div align="justify">
						<p
							style="color: green; font-family: sans-serif; font-size: medium;">
							<i class="fa fa-caret-square-o-right" aria-hidden="true"></i>
							Here we are not giving up.
						</p>
						<p>
							&nbsp;<i class="fa fa-hand-o-right" aria-hidden="true"></i> Our
							expertise team is researching continuously about the Stock
							behavior to extend the features of our product and planning to
							provide a solution globally .we continue to follow our dream
							every day , every week , every month or each fraction of time.
						</p>
					</div>
					<hr>
					<div align="justify">
						<p
							style="color: green; font-family: sans-serif; font-size: medium;">
							<i class="fa fa-user-secret" aria-hidden="true"></i> Strategy for
							lay investors
						</p>
						<p>
							&nbsp; <i class="fa fa-hand-o-right" aria-hidden="true"></i> Our
							product is user-friendly.
						</p>
					</div>
				</div>
			</div>


			<div class="row">
				<div class="col-lg-12">
					<div class="box box-default">
						<div class="box-header with-border">
							<h3 class="box-title">What We are Offer</h3>
						</div>
						<div class="box-body">
							<div class="row" align="justify">
								<div class="col-lg-4">
									<h3 align="center" style="font-family: cursive; color: olive;">
										"<u>Algorithmic predictions</u>"
									</h3>
									<div align="center">
										<img src="<c:url value="/resources/images/equityjudge.jpg"/>" />
									</div>
									<br>
									<p style="color: navy;">
										&nbsp;&nbsp;&nbsp; <i class="fa fa-tag" aria-hidden="true"></i>
										We are offering the Algorithmic predictions on stocks based on
										the share market movements . It gives you the current status
										of the individual stock and what would be the algorithmic
										future status of that stock. Investors may benefits by using
										algorithmic predictions in making fresh
										investment.disinvestment or sanitizing their existing
										holdings.
									</p>
								</div>
								<div class="col-lg-4">
									<h3 align="center" style="font-family: cursive; color: olive;">
										"<u>Portfolio</u>"
									</h3>
									<div align="center">
										<img src="<c:url value="/resources/images/portfolio.jpg"/>" />
									</div>
									<br>
									<p style="color: navy;">
										&nbsp;&nbsp;&nbsp; <i class="fa fa-tag" aria-hidden="true"></i>
										Portfolio tracker provides information like share purchased/sell details
										, long/sort term GAINS, current profit/loss of holdings.</p>									</p>
								</div>
								<div class="col-lg-4">
									<h3 align="center" style="font-family: cursive; color: olive;">
										"<u>Trend</u>"
									</h3>
									<div align="center">
										<img src="<c:url value="/resources/images/graph.jpg"/>" />
									</div>
									<br>
									<p style="color: navy;">
										&nbsp;&nbsp;&nbsp; <i class="fa fa-tag" aria-hidden="true"></i>
										Trend provides the graphical representation of the selected
										stocks over a period of past 1 year for knowledgeable investors.
										 Its allows the user to study 15, 30, 100 and 200 daily
										  moving average and also
										provide the facility to compare the stock movement with
										respect to BSE SENSEX.
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-success">
						<div class="panel-heading">
							<h4>Our Equityjudge Team</h4>
						</div>
						<div class="panel-body">
							<div class="col-lg-2 text-center">
								<img class="img-circle img-responsive img-center"
									src="<c:url value="/resources/images/team/Ramanand Tyagi.jpg"/>"
									alt="">
								<h5>
									Mr.Ramanand Tyagi <br> <small>CEO</small>
								</h5>
							</div>
</div>
<br><hr>
<div class="panel-body">
							<div class="col-lg-2 text-center">
								<img class="img-circle img-responsive img-center"
									src="<c:url value="/resources/images/team/shweta.jpg"/>" alt="">
								<h5>
									kiran<br> <small>Developer</small>
								</h5>
							</div>
							<div class="col-lg-2 text-center">
								<img class="img-circle img-responsive img-center"
									src="<c:url value="/resources/images/team/chetan.jpg"/>" alt="">
								<h5>
									Chetan G<br> <small>Developer</small>
								</h5>
							</div> 
							<div class="col-lg-2 text-center">
								<img class="img-circle img-responsive img-center"
									src="<c:url value="/resources/images/team/chintan.jpg"/>"
									alt="">
								<h5>
									Chintan Joshi <br> <small>Developer</small>
								</h5>
							</div>
							<div class="col-lg-2 text-center">
								<img class="img-circle img-responsive img-center"
									src="<c:url value="/resources/images/team/manish.jpg"/>"
									alt="">
								<h5>
									Manish Kumar <br><small>Developer</small>
								</h5>
							</div>
							<div class="col-lg-2 text-center">
								<img class="img-circle img-responsive img-center"
									src="<c:url value="/resources/images/team/baijnath.jpg"/>" alt="">
								<h5>
									Baijnath Saw<br> <small>Developer</small>
								</h5>
							</div>
							<div class="col-lg-2 text-center">
								<img class="img-circle img-responsive img-center"
									src="<c:url value="/resources/images/team/vikas.jpg"/>" alt="">
								<h5>
									Vikas Kumar <br><small>Developer</small>
								</h5>
							</div>

						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</body>
</html>