<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta charset="UTF-8">
<title>Equityjudge</title>
<!-- <meta name=viewport content="width=device-width, initial-scale=1"> -->
<meta name="charset" content="utf-8" />
<meta http-equiv="content-Type" content="text/html; charset=utf-8" />
<meta name="copyright"
	content="QUALDE DIGITAL SERVICES PVT. LTD. - 2016" />
<meta name="" content="">
<!-- [favicon] begin -->
<link rel="shortcut icon" type="image/x-icon"
	href="<c:url value="/resources/images/favicon.ico"/>" />
<title>Indian equity investment Equityjudge</title>
<meta name="description"
	content="Equityjudge: This is unique website , Probably the best(Success rate 80-100 %) on indian equity shares. The Suggestion are generated by algorithms, based on the modelling of price behaviour ,using pattern recognition techniques.">
<meta name="keywords"
	content="Equityjudge equity invesment online ,best equities to invest in india, equity ,eq,equit,equityjuge,shares,share,sharemarket,stock,stockmarket ,best sharemarket websites,best market research.">





<link id="default-css" rel="stylesheet"
	href="<c:url value="/resources/header/css/style.css"/>" type="text/css"
	media="all" />
<link id="shortcodes-css" rel="stylesheet"
	href="<c:url value="/resources/header/css/shortcodes.css"/>"
	type="text/css" media="all" />
<link id="skin-css" rel="stylesheet"
	href="<c:url value="/resources/header/skins/brown/style.css"/>"
	type="text/css" media="all" />
<link rel="stylesheet"
	href="<c:url value="/resources/header/css/animations.css"/>"
	type="text/css" media="all" />
<link rel="stylesheet"
	href="<c:url value="/resources/header/style.css"/>" type="text/css"
	media="screen" />

<style>
.error {
	color: red;
}
</style>


<link href=" <c:url value="/resources/css/AdminLTE.min.css"/>"
	rel="stylesheet" type="text/css" />

<link rel="stylesheet"
	href="<c:url value="/resources/header/css/font-awesome.min.css"/>"
	type="text/css" media="all" />

<link href="<c:url value="/resources/css/bootstrap.min.css"/>"
	rel="stylesheet" type="text/css" />
	
	
	
	

<script type="text/javascript"
	src="<c:url value="/resources/js/jquery-2.1.4.min.js"/>"></script>
<script type="text/javascript"
	src="<c:url value="/resources/js/hide_data_animated.js"/>"></script>
<script type="text/javascript"
	src="<c:url value="/resources/js/bootstrap.min.js"/>"></script>


<script type="text/javascript"
	src="<c:url value="/resources/js/angular.min.js"/>"></script>
<script type="text/javascript"
	src="<c:url value="/resources/angular/app.js"/>"></script>


<link rel="stylesheet"
	href="<c:url value="/resources/css/nv.d3.min.css"/>" />
	
<script src="<c:url value="/resources/js/d3.min.js"/>"></script>
<script src="<c:url value="/resources/js/nv.d3.min.js"/>"></script>
<script src="<c:url value="/resources/js/angular-nvd3.min.js"/>"></script>

<!--  For Ticker -->
<script src="<c:url value="/resources/dist/ticker/js/endlessRiver.js"/>"></script>
<link rel="stylesheet"
	href="<c:url value="/resources/dist/ticker/css/endlessRiver.css"/>" />


</head>