package com.nivesh.dao;

public interface GraphSqlConstant {

	public static final String SQL_GETLIVE_DATAFEEDS="SELECT OPEN_PRICE,HIGH_PRICE,LOW_PRICE,CLOSE_PRICE,PREV_CLOSE_PRICE,VOLUME,VALUE,AUDIT_DATE_TIME  FROM niv_livedatafeeds WHERE COMPANYNAME=?;";

	public static final String SQL_GETCOMPANYFOR_TICKER="SELECT COMPANYNAME FROM niv_daily_pattern_report WHERE FORMING_DATE = (SELECT MAX(FORMING_DATE) FROM niv_daily_pattern_report WHERE PATTERN_NAME!='UNAVAILABLE') AND (SUGGESTION='STRONG BUY' OR SUGGESTION='BUY') LIMIT 10";
}
	
