// Generated by JavaFromJSON 
//http://javafromjson.dashingrocket.com

package com.nivesh.dto.payment;

public class Payment_request {
	@Override
	public String toString() {
		return "Payment_request [allow_repeated_payments="
				+ allow_repeated_payments + ", purpose=" + purpose
				+ ", buyer_name=" + buyer_name + ", longurl=" + longurl
				+ ", redirect_url=" + redirect_url + ", email_status="
				+ email_status + ", phone=" + phone + ", status=" + status
				+ ", sms_status=" + sms_status + ", created_at=" + created_at
				+ ", shorturl=" + shorturl + ", modified_at=" + modified_at
				+ ", id=" + id + ", amount=" + amount + ", send_email="
				+ send_email + ", send_sms=" + send_sms + ", email=" + email
				+ ", webhook=" + webhook + "]";
	}

	@org.codehaus.jackson.annotate.JsonProperty("allow_repeated_payments")
	private java.lang.Boolean allow_repeated_payments;

 	public void setAllow_repeated_payments(java.lang.Boolean allow_repeated_payments) {
		this.allow_repeated_payments = allow_repeated_payments;
	}

	public java.lang.Boolean getAllow_repeated_payments() {
		return allow_repeated_payments;
	}

	@org.codehaus.jackson.annotate.JsonProperty("purpose")
	private java.lang.String purpose;

 	public void setPurpose(java.lang.String purpose) {
		this.purpose = purpose;
	}

	public java.lang.String getPurpose() {
		return purpose;
	}

	@org.codehaus.jackson.annotate.JsonProperty("buyer_name")
	private java.lang.String buyer_name;

 	public void setBuyer_name(java.lang.String buyer_name) {
		this.buyer_name = buyer_name;
	}

	public java.lang.String getBuyer_name() {
		return buyer_name;
	}

	@org.codehaus.jackson.annotate.JsonProperty("longurl")
	private java.lang.String longurl;

 	public void setLongurl(java.lang.String longurl) {
		this.longurl = longurl;
	}

	public java.lang.String getLongurl() {
		return longurl;
	}

	@org.codehaus.jackson.annotate.JsonProperty("redirect_url")
	private java.lang.String redirect_url;

 	public void setRedirect_url(java.lang.String redirect_url) {
		this.redirect_url = redirect_url;
	}

	public java.lang.String getRedirect_url() {
		return redirect_url;
	}

	@org.codehaus.jackson.annotate.JsonProperty("email_status")
	private java.lang.String email_status;

 	public void setEmail_status(java.lang.String email_status) {
		this.email_status = email_status;
	}

	public java.lang.String getEmail_status() {
		return email_status;
	}

	@org.codehaus.jackson.annotate.JsonProperty("phone")
	private java.lang.String phone;

 	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getPhone() {
		return phone;
	}

	@org.codehaus.jackson.annotate.JsonProperty("status")
	private java.lang.String status;

 	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getStatus() {
		return status;
	}

	@org.codehaus.jackson.annotate.JsonProperty("sms_status")
	private java.lang.String sms_status;

 	public void setSms_status(java.lang.String sms_status) {
		this.sms_status = sms_status;
	}

	public java.lang.String getSms_status() {
		return sms_status;
	}

	@org.codehaus.jackson.annotate.JsonProperty("created_at")
	private java.lang.String created_at;

 	public void setCreated_at(java.lang.String created_at) {
		this.created_at = created_at;
	}

	public java.lang.String getCreated_at() {
		return created_at;
	}

	@org.codehaus.jackson.annotate.JsonProperty("shorturl")
	private java.lang.Object shorturl;

 	public void setShorturl(java.lang.Object shorturl) {
		this.shorturl = shorturl;
	}

	public java.lang.Object getShorturl() {
		return shorturl;
	}

	@org.codehaus.jackson.annotate.JsonProperty("modified_at")
	private java.lang.String modified_at;

 	public void setModified_at(java.lang.String modified_at) {
		this.modified_at = modified_at;
	}

	public java.lang.String getModified_at() {
		return modified_at;
	}

	@org.codehaus.jackson.annotate.JsonProperty("id")
	private java.lang.String id;

 	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getId() {
		return id;
	}

	@org.codehaus.jackson.annotate.JsonProperty("amount")
	private java.lang.String amount;

 	public void setAmount(java.lang.String amount) {
		this.amount = amount;
	}

	public java.lang.String getAmount() {
		return amount;
	}

	@org.codehaus.jackson.annotate.JsonProperty("send_email")
	private java.lang.Boolean send_email;

 	public void setSend_email(java.lang.Boolean send_email) {
		this.send_email = send_email;
	}

	public java.lang.Boolean getSend_email() {
		return send_email;
	}

	@org.codehaus.jackson.annotate.JsonProperty("send_sms")
	private java.lang.Boolean send_sms;

 	public void setSend_sms(java.lang.Boolean send_sms) {
		this.send_sms = send_sms;
	}

	public java.lang.Boolean getSend_sms() {
		return send_sms;
	}

	@org.codehaus.jackson.annotate.JsonProperty("email")
	private java.lang.String email;

 	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public java.lang.String getEmail() {
		return email;
	}

	@org.codehaus.jackson.annotate.JsonProperty("webhook")
	private java.lang.String webhook;

 	public void setWebhook(java.lang.String webhook) {
		this.webhook = webhook;
	}

	public java.lang.String getWebhook() {
		return webhook;
	}

}