package com.nivesh.dto.payment;
/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/



public class Payment {
	@org.codehaus.jackson.annotate.JsonProperty("payment_request")
	private Payment_request payment_request;

 	public void setPayment_request(Payment_request payment_request) {
		this.payment_request = payment_request;
	}

	public Payment_request getPayment_request() {
		return payment_request;
	}

	@org.codehaus.jackson.annotate.JsonProperty("success")
	private java.lang.Boolean success;

 	public void setSuccess(java.lang.Boolean success) {
		this.success = success;
	}

	public java.lang.Boolean getSuccess() {
		return success;
	}

	@Override
	public String toString() {
		return "Payment [payment_request=" + payment_request + ", success="
				+ success + "]";
	}

}